### ISSUE TITLE
Building to 3DS ROM?

### ISSUE THREAD

**Issue by sketchedgrey** [martincohen/Punity#11]
Hi! I was looking around for a hobbyist game engine for the Nintendo 3DS and someone mentioned this gem. Every time I search the web for some sort of documentation for Punity or research material on it the only things that appear are the Unity game engine and some random horror game. So, can you build ROMs or any other executable file format for DS/3DS? If not may someone help me navigate to where I would be able to find such a place?

~~P. S. As of now I won't be able to build the engine. I'm assuming everything here is text base[d], but I could be wrong. May someone please confirm or deny my theory? Thanks!~~

EDIT: Took a look at the source code, silly me no game preview or anything (not that it's a bad thing or anything). Sorry!

**Comment by martincohen** [comment]
@sketchedgrey I was able to build Punity for some ARM based handhelds, but never went into DS/3DS really. Can't even imagine where I'd start doing that really, since these platforms are closed. I'd probably look first at some homebrew OS and respective communities. Punity renders everything on CPU, only the final frame blip is done via OpenGL, which I'm not sure would be fast enough on way limited HW as DS/3DS. Changing Punity to render via OpenGL would be quite a feat and would basically change everything about Punity itself.

Other possible source is looking at SDL2 and it's community. I only found [SDL1.2 ported to 3DS](https://github.com/nop90/SDL-3DS).

**Comment by sketchedgrey** [comment]
> @sketchedgrey I was able to build Punity for some ARM based handhelds, but never went into DS/3DS really. Can't even imagine where I'd start doing that really, since these platforms are closed. I'd probably look first at some homebrew OS and respective communities. Punity renders everything on CPU, only the final frame blip is done via OpenGL, which I'm not sure would be fast enough on way limited HW as DS/3DS. Changing Punity to render via OpenGL would be quite a feat and would basically change everything about Punity itself.
> 
> 
> 
> Other possible source is looking at SDL2 and it's community. I only found [SDL1.2 ported to 3DS](https://github.com/nop90/SDL-3DS).

Alright! If you do ever decide to implement 3DS support let me know! SDL-3DS looks pretty good. Honestly I don't have any practical uses for Punity at the moment but if I do find something I'll... ya know, use Punity.

**Comment by sketchedgrey** [comment]
> 
> 
> @sketchedgrey I was able to build Punity for some ARM based handhelds, but never went into DS/3DS really. Can't even imagine where I'd start doing that really, since these platforms are closed. I'd probably look first at some homebrew OS and respective communities. Punity renders everything on CPU, only the final frame blip is done via OpenGL, which I'm not sure would be fast enough on way limited HW as DS/3DS. Changing Punity to render via OpenGL would be quite a feat and would basically change everything about Punity itself.
> 
> Other possible source is looking at SDL2 and it's community. I only found [SDL1.2 ported to 3DS](https://github.com/nop90/SDL-3DS).

UPDATE: It looks like SDL is a Homebrew application maker, not something I can run from a card. Any other engines, @martincohen ?

**Comment by martincohen** [comment]
SDL (Simple DirectMedia Layer) is a high quality library that provides platform API for input (controllers) and graphics. If you learn how to use it you'll be able to run code that uses it on 3DS (as well as Windows, Mac, Linux, or any other platform that SDL has been ported to). There are many game engines that can run on top of SDL (including Punity).

Of course it's not as straight forward and you'd have to get your hands dirty with some deeper knowledge (for example how to compile and package games for 3DS so you can run them from a card, etc.).

**Comment by martincohen** [comment]
It might be also useful for you to clear out some possible confusion. Punity doesn't have any UI or anything resembling comfort of Unity or Unreal. It's a game framework, a piece of code that solves some of the low level problems for you so you can focus on game code. But it is just a piece of code and a piece of a build script.

I haven't seen a dedicated 3DS game engine in the open. The tech is closed and you have to have Nintendo developer account (or even a dev kit that is not cheap) in order to write games for Nintendo platforms. I know Game Maker and Unity might support Nintendo Switch, but you still need to have Nintendo account/devkit.

The only possible way for a hobbyist is to replace original OS with a homebrew OS and perhaps look at how some of the homebrew games were made (I'm sure authors of such games would share some of their insights). This is why I recommended the SDL library.

Sorry I can't help more, never been dealing with this stuff and all my info is based on very limited sources that I've never studied deeply since I'm not interested in developing for old Nintendo platforms.
